### ISSUE TITLE
I take  a few libraries errors in .net maui

### ISSUE THREAD

**Issue by muhammetfaik** [PacktPublishing/.NET-MAUI-Cross-Platform-Application-Development#4]
I update chapter 5 project .net 8.0 but I have two error.

`
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0176	Member 'PxDatabase.GetDeviceLockData(User)' cannot be accessed with an instance reference; qualify it with a type name instead	PassXYZ.Vault (net8.0-android), PassXYZ.Vault (net8.0-ios), PassXYZ.Vault (net8.0-maccatalyst), PassXYZ.Vault (net8.0-windows10.0.19041.0)	C:\Users\faikm\Desktop\Codes\.NET-MAUI-Cross-Platform-Application-Development\Chapter05\PassXYZ.Vault\Services\UserService.cs	195		
`
`
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0176	Member 'PxDatabase.CreateKeyFile(string, string)' cannot be accessed with an instance reference; qualify it with a type name instead	PassXYZ.Vault (net8.0-android), PassXYZ.Vault (net8.0-ios), PassXYZ.Vault (net8.0-maccatalyst), PassXYZ.Vault (net8.0-windows10.0.19041.0)	C:\Users\faikm\Desktop\Codes\.NET-MAUI-Cross-Platform-Application-Development\Chapter05\PassXYZ.Vault\Services\UserService.cs	206		
`

 this codes in Userservices.cs file:
```csharp
   public string GetDeviceLockData()
   {
       return db.GetDeviceLockData(_user);
   }

   /// <summary>
   /// Recreate a key file from a PxKeyData
   /// </summary>
   /// <param name="data">PxKeyData source</param>
   /// <param name="username">username inside PxKeyData source</param>
   /// <returns>true - created key file, false - failed to create key file.</returns>
   public bool CreateKeyFile(string data, string username)
   {
       return db.CreateKeyFile(data, username);
   }
   ```

**Comment by shugaoye** [comment]
This is the source code for the first edition, which is built for .NET 6. If you wish to build against .NET 8, please refer to the code for the second edition.

https://github.com/PacktPublishing/.NET-MAUI-Cross-Platform-Application-Development-Second-edition

**Comment by bsingha27** [comment]
Hi @muhammetfaik,
We're closing this issue! If you face any further issues on any chapter, please feel free to open a new one.
Thanks.
